# Mirror master to main branches in the engine repository.
on:
  push:
    branches:
      - 'master'

jobs:
  mirror_job:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: Mirror main branch to master branch
    steps:
      - name: Mirror action step
        id: mirror
        uses: google/mirror-branch-action@c6b07e441a7ffc5ae15860c1d0a8107a3a151db8
        with:
          github-token: ${{ secrets.FLUTTERGITHUBBOT_TOKEN }}
          source: 'master'
          dest: 'main'
